# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  Glad_config = debug
  Rits_config = debug
  Sandbox_config = debug
endif
ifeq ($(config),release)
  GLFW_config = release
  Glad_config = release
  Rits_config = release
  Sandbox_config = release
endif
ifeq ($(config),dist)
  GLFW_config = dist
  Glad_config = dist
  Rits_config = dist
  Sandbox_config = dist
endif

PROJECTS := GLFW Glad Rits Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Rits/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C Rits/vendor/Glad -f Makefile config=$(Glad_config)
endif

Rits: GLFW Glad
ifneq (,$(Rits_config))
	@echo "==== Building Rits ($(Rits_config)) ===="
	@${MAKE} --no-print-directory -C Rits -f Makefile config=$(Rits_config)
endif

Sandbox: Rits
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C Rits/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C Rits/vendor/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C Rits -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   Glad"
	@echo "   Rits"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"